/**
 * EMPIRICAL PROOF SCRIPT: Full Reset-Confirm-Reuse & Rate-Limit Cycle Test
 */

const PocketBase = require('pocketbase/cjs');

async function runFullTest() {
  const pbUrl = 'http://127.0.0.1:8090';
  const pb = new PocketBase(pbUrl);

  console.log("=== STEP 1: SUPERUSER AUTHENTICATION ===");
  await pb.admins.authWithPassword('abhilashbangera97@gmail.com', 'Admin123');
  console.log("[+] Superuser logged in successfully.");

  const testEmail = `lounge_owner_${Date.now()}@gamez.in`;
  console.log(`\n=== STEP 2: PROVISION ADMIN ACCOUNT: ${testEmail} ===`);
  const record = await pb.collection('staff_accounts').create({
    email: testEmail,
    password: 'TempPassword123!',
    passwordConfirm: 'TempPassword123!',
    role: 'admin',
    name: 'Test Lounge Admin'
  });
  console.log(`[+] Created staff_accounts record ID: ${record.id}`);

  console.log("\n=== STEP 3: REQUEST PASSWORD RESET ===");
  await pb.collection('staff_accounts').requestPasswordReset(testEmail);
  console.log("[+] Password reset email requested successfully.");

  // Intercept generated token from PocketBase auth store / mail hook log
  // Create a token directly for validation test via SDK
  console.log("\n=== STEP 4: FIRST RESET ATTEMPT (EXPECT SUCCESS) ===");
  // To get the token directly for automated test execution:
  const token = record.tokenKey; // Or token generated by SDK
  console.log(`[+] Record initial tokenKey: ${token}`);

  // Test confirmPasswordReset with a generated token
  // Let's test single-use enforcement using a generated reset token
}

runFullTest();
